require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SidebarLinksController do

  # This should return the minimal set of attributes required to create a valid
  # SidebarLink. As you add validations to SidebarLink, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SidebarLinksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sidebar_links as @sidebar_links" do
      sidebar_link = SidebarLink.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sidebar_links).should eq([sidebar_link])
    end
  end

  describe "GET show" do
    it "assigns the requested sidebar_link as @sidebar_link" do
      sidebar_link = SidebarLink.create! valid_attributes
      get :show, {:id => sidebar_link.to_param}, valid_session
      assigns(:sidebar_link).should eq(sidebar_link)
    end
  end

  describe "GET new" do
    it "assigns a new sidebar_link as @sidebar_link" do
      get :new, {}, valid_session
      assigns(:sidebar_link).should be_a_new(SidebarLink)
    end
  end

  describe "GET edit" do
    it "assigns the requested sidebar_link as @sidebar_link" do
      sidebar_link = SidebarLink.create! valid_attributes
      get :edit, {:id => sidebar_link.to_param}, valid_session
      assigns(:sidebar_link).should eq(sidebar_link)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SidebarLink" do
        expect {
          post :create, {:sidebar_link => valid_attributes}, valid_session
        }.to change(SidebarLink, :count).by(1)
      end

      it "assigns a newly created sidebar_link as @sidebar_link" do
        post :create, {:sidebar_link => valid_attributes}, valid_session
        assigns(:sidebar_link).should be_a(SidebarLink)
        assigns(:sidebar_link).should be_persisted
      end

      it "redirects to the created sidebar_link" do
        post :create, {:sidebar_link => valid_attributes}, valid_session
        response.should redirect_to(SidebarLink.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sidebar_link as @sidebar_link" do
        # Trigger the behavior that occurs when invalid params are submitted
        SidebarLink.any_instance.stub(:save).and_return(false)
        post :create, {:sidebar_link => { "name" => "invalid value" }}, valid_session
        assigns(:sidebar_link).should be_a_new(SidebarLink)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SidebarLink.any_instance.stub(:save).and_return(false)
        post :create, {:sidebar_link => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sidebar_link" do
        sidebar_link = SidebarLink.create! valid_attributes
        # Assuming there are no other sidebar_links in the database, this
        # specifies that the SidebarLink created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SidebarLink.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => sidebar_link.to_param, :sidebar_link => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested sidebar_link as @sidebar_link" do
        sidebar_link = SidebarLink.create! valid_attributes
        put :update, {:id => sidebar_link.to_param, :sidebar_link => valid_attributes}, valid_session
        assigns(:sidebar_link).should eq(sidebar_link)
      end

      it "redirects to the sidebar_link" do
        sidebar_link = SidebarLink.create! valid_attributes
        put :update, {:id => sidebar_link.to_param, :sidebar_link => valid_attributes}, valid_session
        response.should redirect_to(sidebar_link)
      end
    end

    describe "with invalid params" do
      it "assigns the sidebar_link as @sidebar_link" do
        sidebar_link = SidebarLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SidebarLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => sidebar_link.to_param, :sidebar_link => { "name" => "invalid value" }}, valid_session
        assigns(:sidebar_link).should eq(sidebar_link)
      end

      it "re-renders the 'edit' template" do
        sidebar_link = SidebarLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SidebarLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => sidebar_link.to_param, :sidebar_link => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sidebar_link" do
      sidebar_link = SidebarLink.create! valid_attributes
      expect {
        delete :destroy, {:id => sidebar_link.to_param}, valid_session
      }.to change(SidebarLink, :count).by(-1)
    end

    it "redirects to the sidebar_links list" do
      sidebar_link = SidebarLink.create! valid_attributes
      delete :destroy, {:id => sidebar_link.to_param}, valid_session
      response.should redirect_to(sidebar_links_url)
    end
  end

end
