require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ThemeNamesController do

  # This should return the minimal set of attributes required to create a valid
  # ThemeName. As you add validations to ThemeName, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ThemeNamesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all theme_names as @theme_names" do
      theme_name = ThemeName.create! valid_attributes
      get :index, {}, valid_session
      assigns(:theme_names).should eq([theme_name])
    end
  end

  describe "GET show" do
    it "assigns the requested theme_name as @theme_name" do
      theme_name = ThemeName.create! valid_attributes
      get :show, {:id => theme_name.to_param}, valid_session
      assigns(:theme_name).should eq(theme_name)
    end
  end

  describe "GET new" do
    it "assigns a new theme_name as @theme_name" do
      get :new, {}, valid_session
      assigns(:theme_name).should be_a_new(ThemeName)
    end
  end

  describe "GET edit" do
    it "assigns the requested theme_name as @theme_name" do
      theme_name = ThemeName.create! valid_attributes
      get :edit, {:id => theme_name.to_param}, valid_session
      assigns(:theme_name).should eq(theme_name)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ThemeName" do
        expect {
          post :create, {:theme_name => valid_attributes}, valid_session
        }.to change(ThemeName, :count).by(1)
      end

      it "assigns a newly created theme_name as @theme_name" do
        post :create, {:theme_name => valid_attributes}, valid_session
        assigns(:theme_name).should be_a(ThemeName)
        assigns(:theme_name).should be_persisted
      end

      it "redirects to the created theme_name" do
        post :create, {:theme_name => valid_attributes}, valid_session
        response.should redirect_to(ThemeName.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved theme_name as @theme_name" do
        # Trigger the behavior that occurs when invalid params are submitted
        ThemeName.any_instance.stub(:save).and_return(false)
        post :create, {:theme_name => { "name" => "invalid value" }}, valid_session
        assigns(:theme_name).should be_a_new(ThemeName)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ThemeName.any_instance.stub(:save).and_return(false)
        post :create, {:theme_name => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested theme_name" do
        theme_name = ThemeName.create! valid_attributes
        # Assuming there are no other theme_names in the database, this
        # specifies that the ThemeName created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ThemeName.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => theme_name.to_param, :theme_name => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested theme_name as @theme_name" do
        theme_name = ThemeName.create! valid_attributes
        put :update, {:id => theme_name.to_param, :theme_name => valid_attributes}, valid_session
        assigns(:theme_name).should eq(theme_name)
      end

      it "redirects to the theme_name" do
        theme_name = ThemeName.create! valid_attributes
        put :update, {:id => theme_name.to_param, :theme_name => valid_attributes}, valid_session
        response.should redirect_to(theme_name)
      end
    end

    describe "with invalid params" do
      it "assigns the theme_name as @theme_name" do
        theme_name = ThemeName.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ThemeName.any_instance.stub(:save).and_return(false)
        put :update, {:id => theme_name.to_param, :theme_name => { "name" => "invalid value" }}, valid_session
        assigns(:theme_name).should eq(theme_name)
      end

      it "re-renders the 'edit' template" do
        theme_name = ThemeName.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ThemeName.any_instance.stub(:save).and_return(false)
        put :update, {:id => theme_name.to_param, :theme_name => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested theme_name" do
      theme_name = ThemeName.create! valid_attributes
      expect {
        delete :destroy, {:id => theme_name.to_param}, valid_session
      }.to change(ThemeName, :count).by(-1)
    end

    it "redirects to the theme_names list" do
      theme_name = ThemeName.create! valid_attributes
      delete :destroy, {:id => theme_name.to_param}, valid_session
      response.should redirect_to(theme_names_url)
    end
  end

end
